config/routes.rb
Rails.application.routes.draw do
  post 'events/create'

  root to: 'activity#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  after_create_commit { EventBroadcastJob.perform_later self }
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def show
    @event = Event.new
    @events = Event.all.reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
    Event.create! event_params
  end

  private
  def event_params
    params.require(:event).permit(:message)
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/activity/show.html.erb
<h1>Activity</h1>

<%= form_for @event, url: events_create_path(@event) do |f| %>
  <%= f.label :message %>
  <%= f.text_area :message %>
  <%= f.submit %>
<% end %>

<div id="events">
  <%= render @events %>
</div>

app/views/events/_event.html.erb
<div class="event">
	<p><%= event.created_at.to_formatted_s(:short) %>: <%= event.message %></p>
</div>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>